name: Python CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # --- חלק ה-CI (Continuous Integration) ---
  ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pytest
        run: pip install pytest

      - name: Run Tests (CI)
        run: pytest test_app.py

  # --- חלק ה-CD (Continuous Delivery) ---
  cd-build:
    needs: ci-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Docker Image (CD)
        run: docker build -t my-python-app:latest .
